package com.mysite.entity;
// Generated 18 nov. 2016 19:03:38 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */

@Entity
@Table(name = "course")
public class Course implements java.io.Serializable {

	@Id
	@GeneratedValue
	private String code;

	@Column(name = "TITLE")
	private String title;

	@OneToMany
	private Set<CourseSession> courseSessions = new HashSet<>(0);

	public Course() {
	}


	public Course(String code, String title) {
		this.code = code;
		this.title = title;
	}

	public Course(String code, String title, Set<CourseSession> courseSessions) {
		this.code = code;
		this.title = title;
		this.courseSessions = courseSessions;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set getCourseSessions() {
		return this.courseSessions;
	}

	public void setCourseSessions(Set<CourseSession> courseSessions) {
		this.courseSessions = courseSessions;
	}


}


