package com.mysite.entity;
// Generated 18 nov. 2016 19:03:38 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location")
public class Location {


	@Id
	@GeneratedValue
	private Integer id;

	@Column(name = "city")
	private String city;

	@OneToMany
	private Set<CourseSession> courseSessions = new HashSet<>(0);

	public Location() {
	}

	public Location(Integer id) {
		this.id = id;
	}


	public Location(String city) {
		this.city = city;
	}

	public Location(String city, Set<CourseSession> courseSessions) {
		this.city = city;
		this.courseSessions = courseSessions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Set getCourseSessions() {
		return this.courseSessions;
	}

	public void setCourseSessions(Set<CourseSession> courseSessions) {
		this.courseSessions = courseSessions;
	}


	@Override
	public String toString() {
		return this.city;
	}

}


